// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0ImPX5Jl9za23SqO8jYsKHXMlt938j4',
    appId: '1:499376182698:web:42150f66602a95e0e4c7d3',
    messagingSenderId: '499376182698',
    projectId: 'expense-tracker-hp-2026',
    authDomain: 'expense-tracker-hp-2026.firebaseapp.com',
    storageBucket: 'expense-tracker-hp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI8je1CkZsiJH9oSY9Tn9m9317Jeimuto',
    appId: '1:499376182698:android:af43f8c695c84d60e4c7d3',
    messagingSenderId: '499376182698',
    projectId: 'expense-tracker-hp-2026',
    storageBucket: 'expense-tracker-hp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWpXrONjA9mL4MO9vzzVTal3iVxnSEF8',
    appId: '1:499376182698:ios:5a502df67c97f6d8e4c7d3',
    messagingSenderId: '499376182698',
    projectId: 'expense-tracker-hp-2026',
    storageBucket: 'expense-tracker-hp-2026.firebasestorage.app',
    iosBundleId: 'com.example.date',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWpXrONjA9mL4MO9vzzVTal3iVxnSEF8',
    appId: '1:499376182698:ios:5a502df67c97f6d8e4c7d3',
    messagingSenderId: '499376182698',
    projectId: 'expense-tracker-hp-2026',
    storageBucket: 'expense-tracker-hp-2026.firebasestorage.app',
    iosBundleId: 'com.example.date',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW0ImPX5Jl9za23SqO8jYsKHXMlt938j4',
    appId: '1:499376182698:web:c43b4a4aebd0f11ae4c7d3',
    messagingSenderId: '499376182698',
    projectId: 'expense-tracker-hp-2026',
    authDomain: 'expense-tracker-hp-2026.firebaseapp.com',
    storageBucket: 'expense-tracker-hp-2026.firebasestorage.app',
  );
}
